'use client'
import "./globals.css";
import { Header } from "./components/Header/Header";
import styles from "./all.module.css";
import { BlueStrip } from "./components/Bluestrip/blueStrip";
import { register } from "swiper/element/bundle";

// Fonts
import { fontPrincipal } from "./fonts";

// Animations
import { useEffect } from "react";
import { animatePageIn } from "./utils/animations";

// Register Swiper
register();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  // Animação de entrada da página
  useEffect(() => {
    animatePageIn()
  }, [])

  return (
    <html lang="pt-br">
      <body className={`${styles.body} ${fontPrincipal.className} `}>

          {/* Transitions Pages */}
          <div id="banner-1" className="banner"></div>
          <div id="banner-2" className="banner"></div>
          <div id="banner-3" className="banner"></div>
          <div id="banner-4" className="banner"></div>

          <BlueStrip />
          <Header />
          <main className={styles.main}>
              {children}
          </main>

      </body>
    </html>
  );
}
