import { Urbanist } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={urbanist.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
