import { Urbanist } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header/Header";
import styles from "./all.module.css";
import { BlueStrip } from "./components/Bluestrip/blueStrip";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${styles.body} ${urbanist.className} `}>
        <BlueStrip />
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
